In [1]:
import requests
import pandas as pd

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

print("Libraries loaded successfully.")

Libraries loaded successfully.

In [3]:
DATASET_ID = 'd5aa71a8-dcc0-4570-8bcf-bd39deac69fe'
BASE_URL = f"https://data.cms.gov/data-api/v1/dataset/{DATASET_ID}/data"

params = {
    "size": 1000
}

print(BASE_URL)

https://data.cms.gov/data-api/v1/dataset/d5aa71a8-dcc0-4570-8bcf-bd39deac69fe/data

In [4]:
response = requests.get(BASE_URL, params=params)

print(f"Status Code: {response.status_code}")

Status Code: 200

In [5]:
data = response.json()

df = pd.DataFrame(data)

df.head()

,Prscrbr_NPI,Prscrbr_Last_Org_Name,Prscrbr_First_Name,Prscrbr_City,Prscrbr_State_Abrvtn,Prscrbr_State_FIPS,Prscrbr_Type,Prscrbr_Type_Src,Brnd_Name,Gnrc_Name,Tot_Clms,Tot_30day_Fills,Tot_Day_Suply,Tot_Drug_Cst,Tot_Benes,GE65_Sprsn_Flag,GE65_Tot_Clms,GE65_Tot_30day_Fills,GE65_Tot_Drug_Cst,GE65_Tot_Day_Suply,GE65_Bene_Sprsn_Flag,GE65_Tot_Benes
0,1003000126,Enkeshafi,Ardalan,Bethesda,MD,24,Internal Medicine,Claim-Specialty,Abrysvo,"Rsv Vacc, Pref A And Pref B/Pf",20,20,20,5994.01,20,,20,20,5994.01,20,,20
1,1003000126,Enkeshafi,Ardalan,Bethesda,MD,24,Internal Medicine,Claim-Specialty,Boostrix Tdap,"Diphth,pertuss(Acell),tet Vac",12,12,12,648.26,12,,12,12,648.26,12,,12
2,1003000142,Khalil,Rashid,Toledo,OH,39,Anesthesiology,Claim-Specialty,Acetaminophen-Codeine,Acetaminophen With Codeine,24,24,628,362.48,11,#,,,,,*,
3,1003000142,Khalil,Rashid,Toledo,OH,39,Anesthesiology,Claim-Specialty,Amitriptyline Hcl,Amitriptyline Hcl,47,47,1410,271.17,16,,30,30,150.18,900,*,
4,1003000142,Khalil,Rashid,Toledo,OH,39,Anesthesiology,Claim-Specialty,Baclofen,Baclofen,47,47,1395,333.35,26,,33,33,222.14,975,#,

In [6]:
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows    : 1000
Columns : 22

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Prscrbr_NPI            1000 non-null   object
 1   Prscrbr_Last_Org_Name  1000 non-null   object
 2   Prscrbr_First_Name     1000 non-null   object
 3   Prscrbr_City           1000 non-null   object
 4   Prscrbr_State_Abrvtn   1000 non-null   object
 5   Prscrbr_State_FIPS     1000 non-null   object
 6   Prscrbr_Type           1000 non-null   object
 7   Prscrbr_Type_Src       1000 non-null   object
 8   Brnd_Name              1000 non-null   object
 9   Gnrc_Name              1000 non-null   object
 10  Tot_Clms               1000 non-null   object
 11  Tot_30day_Fills        1000 non-null   object
 12  Tot_Day_Suply          1000 non-null   object
 13  Tot_Drug_Cst           1000 non-null   object
 14  Tot_Benes              1000 non-null   object
 15  GE65_Sprsn_Flag        1000 non-null   object
 16  GE65_Tot_Clms          1000 non-null   object
 17  GE65_Tot_30day_Fills   1000 non-null   object
 18  GE65_Tot_Drug_Cst      1000 non-null   object
 19  GE65_Tot_Day_Suply     1000 non-null   object
 20  GE65_Bene_Sprsn_Flag   1000 non-null   object
 21  GE65_Tot_Benes         1000 non-null   object
dtypes: object(22)
memory usage: 172.0+ KB

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Prscrbr_NPI            1000 non-null   object
 1   Prscrbr_Last_Org_Name  1000 non-null   object
 2   Prscrbr_First_Name     1000 non-null   object
 3   Prscrbr_City           1000 non-null   object
 4   Prscrbr_State_Abrvtn   1000 non-null   object
 5   Prscrbr_State_FIPS     1000 non-null   object
 6   Prscrbr_Type           1000 non-null   object
 7   Prscrbr_Type_Src       1000 non-null   object
 8   Brnd_Name              1000 non-null   object
 9   Gnrc_Name              1000 non-null   object
 10  Tot_Clms               1000 non-null   object
 11  Tot_30day_Fills        1000 non-null   object
 12  Tot_Day_Suply          1000 non-null   object
 13  Tot_Drug_Cst           1000 non-null   object
 14  Tot_Benes              1000 non-null   object
 15  GE65_Sprsn_Flag        1000 non-null   object
 16  GE65_Tot_Clms          1000 non-null   object
 17  GE65_Tot_30day_Fills   1000 non-null   object
 18  GE65_Tot_Drug_Cst      1000 non-null   object
 19  GE65_Tot_Day_Suply     1000 non-null   object
 20  GE65_Bene_Sprsn_Flag   1000 non-null   object
 21  GE65_Tot_Benes         1000 non-null   object
dtypes: object(22)
memory usage: 172.0+ KB

In [9]:
df.describe(include="all")

,Prscrbr_NPI,Prscrbr_Last_Org_Name,Prscrbr_First_Name,Prscrbr_City,Prscrbr_State_Abrvtn,Prscrbr_State_FIPS,Prscrbr_Type,Prscrbr_Type_Src,Brnd_Name,Gnrc_Name,Tot_Clms,Tot_30day_Fills,Tot_Day_Suply,Tot_Drug_Cst,Tot_Benes,GE65_Sprsn_Flag,GE65_Tot_Clms,GE65_Tot_30day_Fills,GE65_Tot_Drug_Cst,GE65_Tot_Day_Suply,GE65_Bene_Sprsn_Flag,GE65_Tot_Benes
count,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
unique,45,45,44,44,23,23,22,3,368,324,205,406,680,998,99,3,151,255,558,377,3,60
top,1003002817,Iglesias,Nayvis,Doral,FL,12,Family Practice,Claim-Specialty,Hydrocodone-Acetaminophen,Hydrocodone/Acetaminophen,12,13,360,40.49,,,,,,,*,
freq,205,205,205,205,253,253,411,771,13,13,61,33,17,2,529,585,415,415,415,415,550,860

In [12]:
df.isnull().sum()

Prscrbr_NPI              0
Prscrbr_Last_Org_Name    0
Prscrbr_First_Name       0
Prscrbr_City             0
Prscrbr_State_Abrvtn     0
Prscrbr_State_FIPS       0
Prscrbr_Type             0
Prscrbr_Type_Src         0
Brnd_Name                0
Gnrc_Name                0
Tot_Clms                 0
Tot_30day_Fills          0
Tot_Day_Suply            0
Tot_Drug_Cst             0
Tot_Benes                0
GE65_Sprsn_Flag          0
GE65_Tot_Clms            0
GE65_Tot_30day_Fills     0
GE65_Tot_Drug_Cst        0
GE65_Tot_Day_Suply       0
GE65_Bene_Sprsn_Flag     0
GE65_Tot_Benes           0
dtype: int64

In [13]:
response.headers

{'Content-Language': 'en', 'Content-Security-Policy': 'report-uri /report-csp-violation', 'Content-Type': 'application/json', 'ETag': '"1784268803-gzip"', 'Last-Modified': 'Fri, 17 Jul 2026 06:13:23 GMT', 'Referrer-Policy': 'no-referrer-when-downgrade', 'X-Age': '0', 'X-AH-Environment': 'prod', 'x-akamai-original-url': '08ff4c8072129a48657f3e6043a1820662e60637', 'X-Consumer-ID': '07eafadc-1bac-4607-8441-20c35fa46f17', 'X-Content-Type-Options': 'nosniff', 'X-Drupal-Dynamic-Cache': 'HIT', 'X-File-System-Cache': 'MISS', 'X-Frame-Options': 'SAMEORIGIN', 'X-Generator': 'Drupal 10 (https://www.drupal.org)', 'X-Request-ID': 'v-9db47284-81a6-11f1-a023-93c36609d3a1', 'X-XSS-Protection': '1; mode=block, 1; mode=block', 'Content-Encoding': 'br', 'Expires': 'Fri, 17 Jul 2026 06:13:24 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Fri, 17 Jul 2026 06:13:24 GMT', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive, Transfer-Encoding', 'Strict-Transport-Security': 'max-age=31536000 ; includeSubDomains ; preload', 'Akamai-GRN': '0.b1243e17.1784268803.10a0347b'}

In [14]:
response.url

'https://data.cms.gov/data-api/v1/dataset/d5aa71a8-dcc0-4570-8bcf-bd39deac69fe/data?size=1000'

In [15]:
len(data)

1000

In [16]:
stats_url = f"https://data.cms.gov/data-api/v1/dataset/{DATASET_ID}/data/stats"

stats = requests.get(stats_url)

stats.json()

{'found_rows': 28023892, 'total_rows': 28023892}