In [44]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

df = pd.read_csv(
    "../data/raw/cms_partd_raw.csv",
    low_memory=False
)

df.head()

,Prscrbr_NPI,Prscrbr_Last_Org_Name,Prscrbr_First_Name,Prscrbr_City,Prscrbr_State_Abrvtn,Prscrbr_State_FIPS,Prscrbr_Type,Prscrbr_Type_Src,Brnd_Name,Gnrc_Name,Tot_Clms,Tot_30day_Fills,Tot_Day_Suply,Tot_Drug_Cst,Tot_Benes,GE65_Sprsn_Flag,GE65_Tot_Clms,GE65_Tot_30day_Fills,GE65_Tot_Drug_Cst,GE65_Tot_Day_Suply,GE65_Bene_Sprsn_Flag,GE65_Tot_Benes
0,1003000126,Enkeshafi,Ardalan,Bethesda,MD,24,Internal Medicine,Claim-Specialty,Abrysvo,"Rsv Vacc, Pref A And Pref B/Pf",20,20.0,20,5994.01,20.0,NaN,20.0,20.0,5994.01,20.0,NaN,20.0
1,1003000126,Enkeshafi,Ardalan,Bethesda,MD,24,Internal Medicine,Claim-Specialty,Boostrix Tdap,"Diphth,pertuss(Acell),tet Vac",12,12.0,12,648.26,12.0,NaN,12.0,12.0,648.26,12.0,NaN,12.0
2,1003000142,Khalil,Rashid,Toledo,OH,39,Anesthesiology,Claim-Specialty,Acetaminophen-Codeine,Acetaminophen With Codeine,24,24.0,628,362.48,11.0,#,NaN,NaN,NaN,NaN,*,NaN
3,1003000142,Khalil,Rashid,Toledo,OH,39,Anesthesiology,Claim-Specialty,Amitriptyline Hcl,Amitriptyline Hcl,47,47.0,1410,271.17,16.0,NaN,30.0,30.0,150.18,900.0,*,NaN
4,1003000142,Khalil,Rashid,Toledo,OH,39,Anesthesiology,Claim-Specialty,Baclofen,Baclofen,47,47.0,1395,333.35,26.0,NaN,33.0,33.0,222.14,975.0,#,NaN

In [45]:
df_clean = df.copy()

In [46]:
object_columns = df_clean.select_dtypes(include="object").columns

df_clean[object_columns] = (
    df_clean[object_columns]
    .apply(lambda col: col.str.strip())
)

In [47]:
df_clean.head()

,Prscrbr_NPI,Prscrbr_Last_Org_Name,Prscrbr_First_Name,Prscrbr_City,Prscrbr_State_Abrvtn,Prscrbr_State_FIPS,Prscrbr_Type,Prscrbr_Type_Src,Brnd_Name,Gnrc_Name,Tot_Clms,Tot_30day_Fills,Tot_Day_Suply,Tot_Drug_Cst,Tot_Benes,GE65_Sprsn_Flag,GE65_Tot_Clms,GE65_Tot_30day_Fills,GE65_Tot_Drug_Cst,GE65_Tot_Day_Suply,GE65_Bene_Sprsn_Flag,GE65_Tot_Benes
0,1003000126,Enkeshafi,Ardalan,Bethesda,MD,24,Internal Medicine,Claim-Specialty,Abrysvo,"Rsv Vacc, Pref A And Pref B/Pf",20,20.0,20,5994.01,20.0,NaN,20.0,20.0,5994.01,20.0,NaN,20.0
1,1003000126,Enkeshafi,Ardalan,Bethesda,MD,24,Internal Medicine,Claim-Specialty,Boostrix Tdap,"Diphth,pertuss(Acell),tet Vac",12,12.0,12,648.26,12.0,NaN,12.0,12.0,648.26,12.0,NaN,12.0
2,1003000142,Khalil,Rashid,Toledo,OH,39,Anesthesiology,Claim-Specialty,Acetaminophen-Codeine,Acetaminophen With Codeine,24,24.0,628,362.48,11.0,#,NaN,NaN,NaN,NaN,*,NaN
3,1003000142,Khalil,Rashid,Toledo,OH,39,Anesthesiology,Claim-Specialty,Amitriptyline Hcl,Amitriptyline Hcl,47,47.0,1410,271.17,16.0,NaN,30.0,30.0,150.18,900.0,*,NaN
4,1003000142,Khalil,Rashid,Toledo,OH,39,Anesthesiology,Claim-Specialty,Baclofen,Baclofen,47,47.0,1395,333.35,26.0,NaN,33.0,33.0,222.14,975.0,#,NaN

In [48]:
#standardize column names
df_clean.columns = (
    df_clean.columns
        .str.lower()
)

In [49]:
df_clean.dtypes

prscrbr_npi                int64
prscrbr_last_org_name     object
prscrbr_first_name        object
prscrbr_city              object
prscrbr_state_abrvtn      object
prscrbr_state_fips        object
prscrbr_type              object
prscrbr_type_src          object
brnd_name                 object
gnrc_name                 object
tot_clms                   int64
tot_30day_fills          float64
tot_day_suply              int64
tot_drug_cst             float64
tot_benes                float64
ge65_sprsn_flag           object
ge65_tot_clms            float64
ge65_tot_30day_fills     float64
ge65_tot_drug_cst        float64
ge65_tot_day_suply       float64
ge65_bene_sprsn_flag      object
ge65_tot_benes           float64
dtype: object

In [50]:
df_clean["prscrbr_state_fips"].sort_values().unique()

array(['01', '02', '04', '05', '06', '08', '09', '10', '11', '12', '13',
       '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25',
       '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36',
       '37', '38', '39', '40', '41', '42', '44', '45', '46', '47', '48',
       '49', '50', '51', '53', '54', '55', '56', '66', '72', '78', '9E'],
      dtype=object)

In [51]:
df_clean["ge65_sprsn_flag"].value_counts(dropna=False)

ge65_sprsn_flag
NaN    275530
#      167976
*       56494
Name: count, dtype: int64

In [52]:
df_clean["ge65_bene_sprsn_flag"].value_counts(dropna=False)

ge65_bene_sprsn_flag
*      291758
#      147853
NaN     60389
Name: count, dtype: int64

In [53]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 22 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   prscrbr_npi            500000 non-null  int64
 1   prscrbr_last_org_name  500000 non-null  object
 2   prscrbr_first_name     500000 non-null  object
 3   prscrbr_city           500000 non-null  object
 4   prscrbr_state_abrvtn   500000 non-null  object
 5   prscrbr_state_fips     500000 non-null  object
 6   prscrbr_type           500000 non-null  object
 7   prscrbr_type_src       500000 non-null  object
 8   brnd_name              500000 non-null  object
 9   gnrc_name              500000 non-null  object
 10  tot_clms               500000 non-null  int64
 11  tot_30day_fills        500000 non-null  float64
 12  tot_day_suply          500000 non-null  int64
 13  tot_drug_cst           500000 non-null  float64
 14  tot_benes              228305 non-null  float64
 15  ge65_sprsn_flag        224470 non-null  object
 16  ge65_tot_clms          275530 non-null  float64
 17  ge65_tot_30day_fills   275530 non-null  float64
 18  ge65_tot_drug_cst      275530 non-null  float64
 19  ge65_tot_day_suply     275530 non-null  float64
 20  ge65_bene_sprsn_flag   439611 non-null  object
 21  ge65_tot_benes         60389 non-null   float64
dtypes: float64(8), int64(3), object(11)
memory usage: 83.9+ MB

In [54]:
import numpy as np

df_clean["ge65_claims_suppression_status"] = np.select(
    [
        df_clean["ge65_sprsn_flag"] == "*",
        df_clean["ge65_sprsn_flag"] == "#",
        df_clean["ge65_sprsn_flag"].isna()
    ],
    [
        "Primary Suppression",
        "Counter Suppression",
        "Not Suppressed"
    ],
    default="Unknown"
)

In [55]:
df_clean["ge65_beneficiary_suppression_status"] = np.select(
    [
        df_clean["ge65_bene_sprsn_flag"] == "*",
        df_clean["ge65_bene_sprsn_flag"] == "#",
        df_clean["ge65_bene_sprsn_flag"].isna()
    ],
    [
        "Primary Suppression",
        "Counter Suppression",
        "Not Suppressed"
    ],
    default="Unknown"
)

In [56]:
df_clean[
    [
        "ge65_sprsn_flag",
        "ge65_claims_suppression_status"
    ]
].head(10)

  ge65_sprsn_flag ge65_claims_suppression_status
0             NaN                 Not Suppressed
1             NaN                 Not Suppressed
2               #            Counter Suppression
3             NaN                 Not Suppressed
4             NaN                 Not Suppressed
5               *            Primary Suppression
6               *            Primary Suppression
7             NaN                 Not Suppressed
8               #            Counter Suppression
9             NaN                 Not Suppressed

In [57]:
df_clean[
    [
        "ge65_bene_sprsn_flag",
        "ge65_beneficiary_suppression_status"
    ]
].head(10)

  ge65_bene_sprsn_flag ge65_beneficiary_suppression_status
0                  NaN                      Not Suppressed
1                  NaN                      Not Suppressed
2                    *                 Primary Suppression
3                    *                 Primary Suppression
4                    #                 Counter Suppression
5                    *                 Primary Suppression
6                    *                 Primary Suppression
7                    *                 Primary Suppression
8                    #                 Counter Suppression
9                    #                 Counter Suppression

In [58]:
df_clean.info()
df_clean.isnull().sum()
df_clean.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 24 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   prscrbr_npi                          500000 non-null  int64
 1   prscrbr_last_org_name                500000 non-null  object
 2   prscrbr_first_name                   500000 non-null  object
 3   prscrbr_city                         500000 non-null  object
 4   prscrbr_state_abrvtn                 500000 non-null  object
 5   prscrbr_state_fips                   500000 non-null  object
 6   prscrbr_type                         500000 non-null  object
 7   prscrbr_type_src                     500000 non-null  object
 8   brnd_name                            500000 non-null  object
 9   gnrc_name                            500000 non-null  object
 10  tot_clms                             500000 non-null  int64
 11  tot_30day_fills                      500000 non-null  float64
 12  tot_day_suply                        500000 non-null  int64
 13  tot_drug_cst                         500000 non-null  float64
 14  tot_benes                            228305 non-null  float64
 15  ge65_sprsn_flag                      224470 non-null  object
 16  ge65_tot_clms                        275530 non-null  float64
 17  ge65_tot_30day_fills                 275530 non-null  float64
 18  ge65_tot_drug_cst                    275530 non-null  float64
 19  ge65_tot_day_suply                   275530 non-null  float64
 20  ge65_bene_sprsn_flag                 439611 non-null  object
 21  ge65_tot_benes                       60389 non-null   float64
 22  ge65_claims_suppression_status       500000 non-null  object
 23  ge65_beneficiary_suppression_status  500000 non-null  object
dtypes: float64(8), int64(3), object(13)
memory usage: 91.6+ MB

,prscrbr_npi,prscrbr_last_org_name,prscrbr_first_name,prscrbr_city,prscrbr_state_abrvtn,prscrbr_state_fips,prscrbr_type,prscrbr_type_src,brnd_name,gnrc_name,tot_clms,tot_30day_fills,tot_day_suply,tot_drug_cst,tot_benes,ge65_sprsn_flag,ge65_tot_clms,ge65_tot_30day_fills,ge65_tot_drug_cst,ge65_tot_day_suply,ge65_bene_sprsn_flag,ge65_tot_benes,ge65_claims_suppression_status,ge65_beneficiary_suppression_status
0,1003000126,Enkeshafi,Ardalan,Bethesda,MD,24,Internal Medicine,Claim-Specialty,Abrysvo,"Rsv Vacc, Pref A And Pref B/Pf",20,20.0,20,5994.01,20.0,NaN,20.0,20.0,5994.01,20.0,NaN,20.0,Not Suppressed,Not Suppressed
1,1003000126,Enkeshafi,Ardalan,Bethesda,MD,24,Internal Medicine,Claim-Specialty,Boostrix Tdap,"Diphth,pertuss(Acell),tet Vac",12,12.0,12,648.26,12.0,NaN,12.0,12.0,648.26,12.0,NaN,12.0,Not Suppressed,Not Suppressed
2,1003000142,Khalil,Rashid,Toledo,OH,39,Anesthesiology,Claim-Specialty,Acetaminophen-Codeine,Acetaminophen With Codeine,24,24.0,628,362.48,11.0,#,NaN,NaN,NaN,NaN,*,NaN,Counter Suppression,Primary Suppression
3,1003000142,Khalil,Rashid,Toledo,OH,39,Anesthesiology,Claim-Specialty,Amitriptyline Hcl,Amitriptyline Hcl,47,47.0,1410,271.17,16.0,NaN,30.0,30.0,150.18,900.0,*,NaN,Not Suppressed,Primary Suppression
4,1003000142,Khalil,Rashid,Toledo,OH,39,Anesthesiology,Claim-Specialty,Baclofen,Baclofen,47,47.0,1395,333.35,26.0,NaN,33.0,33.0,222.14,975.0,#,NaN,Not Suppressed,Counter Suppression

In [59]:
# Save the cleaned dataset
df_clean.to_csv(
    "../data/processed/cms_partd_clean.csv",
    index=False
)

print("✅ Cleaned dataset saved successfully!")

✅ Cleaned dataset saved successfully!

### 1. Total Beneficiaries (`tot_benes`)

The `tot_benes` column contains beneficiary counts for each Provider–Drug combination.

According to the CMS documentation, beneficiary counts between **1 and 10** are suppressed to protect patient privacy. These suppressed values are published as blank cells, which are interpreted by pandas as `NaN`.

**Decision:** Preserve the `NaN` values. No imputation or replacement is performed.

---

### 2. GE65 Metrics Suppression

The following columns represent prescribing metrics for beneficiaries aged 65 years and older:

- `ge65_tot_clms`

- `ge65_tot_30day_fills`

- `ge65_tot_day_suply`

- `ge65_tot_drug_cst`

These metrics are controlled by the `ge65_sprsn_flag` column.

| Flag | Meaning |

|------|---------|

| `*` | Primary suppression |

| `#` | Counter suppression |

| Blank (`NaN` in pandas) | No suppression |

When the suppression flag contains `*` or `#`, the corresponding GE65 metric values are intentionally hidden by CMS and appear as `NaN`.

**Decision:** Preserve all suppressed values without modification.

---

### 3. GE65 Beneficiary Count

The `ge65_tot_benes` column represents the number of Medicare beneficiaries aged 65 years and older.

This column is governed by a separate suppression flag: `ge65_bene_sprsn_flag`.

| Flag | Meaning |

|------|---------|

| `*` | Primary suppression |

| `#` | Counter suppression |

| Blank (`NaN` in pandas) | No suppression |

Beneficiary counts are subject to stricter privacy rules than claim metrics, resulting in a larger number of suppressed values.

**Decision:** Preserve all suppressed values without modification.

---

### Data Cleaning Decision

The missing values observed in these columns represent **documented CMS privacy suppression rules rather than data quality issues**.

Therefore:

- No missing values are imputed.

- No missing values are replaced with zero.

- Original CMS suppression logic is preserved.

- Human-readable suppression status columns are created to improve downstream SQL analysis and Power BI reporting while retaining the original raw data.

In [60]:
df_clean.columns

Index(['prscrbr_npi', 'prscrbr_last_org_name', 'prscrbr_first_name',
       'prscrbr_city', 'prscrbr_state_abrvtn', 'prscrbr_state_fips',
       'prscrbr_type', 'prscrbr_type_src', 'brnd_name', 'gnrc_name',
       'tot_clms', 'tot_30day_fills', 'tot_day_suply', 'tot_drug_cst',
       'tot_benes', 'ge65_sprsn_flag', 'ge65_tot_clms', 'ge65_tot_30day_fills',
       'ge65_tot_drug_cst', 'ge65_tot_day_suply', 'ge65_bene_sprsn_flag',
       'ge65_tot_benes', 'ge65_claims_suppression_status',
       'ge65_beneficiary_suppression_status'],
      dtype='object')

In [61]:
duplicates = df_clean.duplicated(
    subset=["prscrbr_npi", "brnd_name", "gnrc_name"]
).sum()

print(duplicates)

0